# Generated by Django 6.0.2 on 2026-03-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('create_customuser', 'Can create users via admin UI'), ('edit_customuser', 'Can edit users via admin UI')]},
        ),
    ]
